enum ActionTypes {
  SELECT_CITY_SUGGESTION = 'SELECT_CITY_SUGGESTION',
  SELECT_COUNTRY_SUGGESTION = 'SELECT_COUNTRY_SUGGESTION',

  CITY_SUGGESTION_SELECTED = 'CITY_SUGGESTION_SELECTED',
  COUNTRY_SUGGESTION_SELECTED = 'COUNTRY_SUGGESTION_SELECTED',
  
  GET_SUGGESTIONS_COUNTRY = 'GET_SUGGESTIONS_COUNTRY',
  GET_SUGGESTIONS_CITY = 'GET_SUGGESTIONS_CITY',
  
  COUNTRY_SUGGESTIONS_RCVD = 'COUNTRY_SUGGESTIONS_RCVD',
  CITY_SUGGESTIONS_RCVD = 'CITY_SUGGESTIONS_RCVD',
  
  CLEAR_SUGGESTIONS_COUNTRY = 'CLEAR_SUGGESTIONS_COUNTRY',
  CLEAR_SUGGESTIONS_CITY = 'CLEAR_SUGGESTIONS_CITY',

  CLEAR_SUGGESTIONS_RCVD_CITY = 'CLEAR_SUGGESTIONS_RCVD_CITY',
  CLEAR_SUGGESTIONS_RCVD_COUNTRY = 'CLEAR_SUGGESTIONS_RCVD_COUNTRY',

  LOADING_COUNTRY_SUGGESTIONS = 'LOADING_COUNTRY_SUGGESTIONS',
  COUNTRY_SUGGESTIONS_LOADED = 'COUNTRY_SUGGESTIONS_LOADED',
  
  LOADING_CITY_SUGGESTIONS = 'LOADING_CITY_SUGGESTIONS',
  CITY_SUGGESTIONS_LOADED = 'CITY_SUGGESTIONS_LOADED',

  GET_WEATHER_FORECAST = 'GET_WEATHER_FORECAST',
  WEATHER_FORECAST_RECIEVED = 'WEATHER_FORECAST_RECIEVED',

  LOADING_FORECAST = 'LOADING_FORECAST',
  LOADED_FORECAST = 'LOADED_FORECAST',

  UPDATE_MODE = 'UPDATE_MODE',
};

export default ActionTypes;
